---
title: "HL_DE_analysis-iTALK_visualization"
author: "Stacy Hung"
date: "18/08/2020"
output: html_document
---

## Visualize interactions 

```{r}
library(iTALK)
library(dplyr)
```

## Visualization of interactions based on normalized expression (not DE)

```{r}
par(mfrow = c(1,2))
res <- NULL

# find top 50 percent highly expressed genes
highly_exprs_genes <- rawParse(data.GOI, top_genes = 100, stats='mean')
expr.CXC_genes <- highly_exprs_genes

# NB: CXC receptor-ligand pairs only produce results for the cytokine communication type, so we don't
#     to iterate through all the communication types (e.g. growth facter, etc.)
comm_type <- 'cytokine'
res <- FindLR(expr.CXC_genes, datatype = 'mean count', comm_type = comm_type)
res <- res[ order(res$cell_from_mean_exprs*res$cell_to_mean_exprs, decreasing = T), ]

NetView(res_cat, col = cell_col, vertex.label.cex = 1, arrow.width = 1, edge.max.width = 5)
LRPlot(res_cat, datatype = 'mean count', cell_col = cell_col, 
       link.arr.lwd = res_cat$cell_from_mean_exprs,
       link.arr.width = res_cat$cell_to_mean_exprs)
```

## Visualize differential expression for specified genes and cell types

```{r}
library(tidyr)

LR.db <- iTALK:::database # database of LR interactions --> uses Ligand.ApprovedSymbol and Receptor.ApprovedSymbol
# read in additional interactions
LR.db.to_add <- read.table("~/Documents/sc_HL_relapse/iTALK/LR_database_additions_v2.txt", sep = "\t", header = TRUE)
LR.db <- rbind(LR.db, LR.db.to_add)

comm_list <- c('growth factor','other','cytokine','checkpoint')
cell_col <- c("B cells" = "darkslateblue",
              "Helper T cells" = "slategray4",
              "Treg" = "hotpink3", 
              "B cells, macrophages" = "royalblue1", 
              "Naive T cells" = "aquamarine3",
              "CTL" = "olivedrab4",
              "Treg proliferation"="firebrick3",
              "GCB"="darkorange",
              "B and T mix"="grey44",
              "Proliferation"="mediumpurple1",
              "NK cells"="bisque3",
              "Plasmacytoid DCs"="magenta3",
              "Macrophage"="green3",
              "Plasma cell"="purple")

# function that filters for cell type and gene and returns ligand-receptor interactions in given DE dataset
# default is to filter for macrophage, proliferation and T cell subtypes and filter for CXC genes
getLR <- function(de.df, gene_list, file_name_prefix, width, height) {
  res.all <- NULL
  
  #split "comparison" column by "_" and take the first split element to be cell_type
  de.df <- separate(data = de.df, col = comparison, into = c("cell_type", "group1"), sep = "\\_")

  keeps <- c("gene", "cell_type", "avg_logFC", "p_val", "p_val_adj")
  de.df <- de.df[ keeps ]
  
  keeps.rename <- c("gene", "cell_type", "logFC", "p.value", "q.value")
  colnames(de.df) <- keeps.rename
  
  # filter for cell types of interest
  cell_types.keep <- c("Macrophage", "Treg proliferation", "Helper T cells", "Treg", "CTL", "GCB", "Plasma cell", "Plasmacytoid DCs")
  de.cell_types <- subset(de.df, de.df$cell_type %in% cell_types.keep)
  
  # get expanded list from LR DB (i.e. for list of input genes, get all matching receptors / ligands)
  matching_receptors <- unique(LR.db[ LR.db$Ligand.ApprovedSymbol %in% gene_list , ]$Receptor.ApprovedSymbol)
  matching_ligands <- unique(LR.db[ LR.db$Receptor.ApprovedSymbol %in% gene_list , ]$Ligand.ApprovedSymbol)
  gene_list <- unique(c(gene_list, matching_ligands, matching_receptors))
  
  # filter for genes of interest
  de.GOI <- de.cell_types[ de.cell_types$gene %in% gene_list , ]
  # de.GOI <- de.cell_types[grep("CXC", de.cell_types$gene), ]
  
  # for each type of communication, plot LR results (if there is any)
  for(comm_type in comm_list) {
      # get LR pairs for comm_type of interest
    res <- FindLR(de.GOI, datatype = 'DEG', comm_type = comm_type, database = LR.db)
    # res <- FindLR(de.GOI, datatype = 'DEG', comm_type = comm_type)
    res <- res[order(abs(res$cell_from_logFC*res$cell_to_logFC), decreasing = TRUE), ]
  
    # if (nrow(res) > 0) {
    #   file_name <- paste(file_name_prefix, "-",  comm_type, ".pdf", sep = "")
    #   pdf(file_name, width = width, height = height)
    #   
    #   LRPlot(res, datatype = 'DEG', cell_col = cell_col, 
    #          link.arr.lwd = res$cell_from_logFC, 
    #          link.arr.width = res$cell_to_logFC)
    # 
    #   dev.off()
    # }
    res.all <- rbind(res.all, res)
  }
  
  if (nrow(res.all) > 0) {
    file_name <- paste(file_name_prefix, "-all_comm_types", ".pdf", sep = "")
    pdf(file_name, width = width, height = height)
    LRPlot(res.all, datatype = 'DEG', 
           cell_col = cell_col, 
           link.arr.lwd = res.all$cell_from_logFC, 
           link.arr.width = res.all$cell_to_logFC)
    dev.off()
    
    NetView(res.all, col = cell_col, vertex.label.cex = 1, arrow.width = 1, edge.max.width = 5)
  }

  return(res.all)
}

```

## Current DE analyses

```{r}
# read in the DE results
de.diag_v_refractory <- read.table("~/Documents/sc_HL_relapse/seurat/output/LATEST/DE_analysis/min_3_cells_per_group/de.diag_vs_refractory.cell_types.txt", sep = "\t", header = TRUE)
de.diag_v_early_rel <- read.table("~/Documents/sc_HL_relapse/seurat/output/LATEST/DE_analysis/min_3_cells_per_group/de.diag_vs_early_relapse.cell_types.txt", sep = "\t", header = TRUE)
de.diag_v_rel <- read.table("~/Documents/sc_HL_relapse/seurat/output/LATEST/DE_analysis/min_3_cells_per_group/de.diag_vs_rel.cell_types.txt", sep = "\t", header = TRUE)
de.diag_v_late_rel <- read.table("~/Documents/sc_HL_relapse/seurat/output/LATEST/DE_analysis/min_3_cells_per_group/de.diag_vs_late_relapse.cell_types.txt", sep = "\t", header = TRUE)
de.hl_vs_rln <- read.table("~/Documents/sc_HL_relapse/seurat/output/LATEST/DE_analysis/min_3_cells_per_group/de.hl_vs_rln.cell_types.txt", sep = "\t", header = TRUE)

# ##################################################
# LR interactions for Macrophage/pDC and Tcell genes: 
#   T cell genes:             LAG3, Galectin3 (LGALS3), FGL-1 (FGL1), LSECtin (CLEC4G)
#   Macrophage / pDC genes:   HLA-DP (HLA-DPA1, HLA-DPB1), HLA-DQ (HLA-DQA1, HLA-DQB1, HLA-DQB1-AS1, HLA-DQA2, HLA-DQB2), HLA-DR (HLA-DRA, HLA-DRB5, HLA-DRB1)
# ##################################################

gene_list <- c("HLA-DPA1", "HLA-DPB1", "HLA-DQA1", "HLA-DQB1", "HLA-DQB1-AS1", "HLA-DQA2", "HLA-DQB2", "HLA-DRA", "HLA-DRB5", "HLA-DRB1")

# diagonstic vs. refractory
res <- getLR(de.df = de.diag_v_refractory, gene_list = gene_list,
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_rel-mhcII_genes", 5, 5)
# 0 results

# diagonstic vs. early relapse
res <- getLR(de.df = de.diag_v_early_rel, gene_list = gene_list,
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_early_rel-mhcII_genes", 5, 5)

# diagonstic vs. relapse
res <- getLR(de.df = de.diag_v_rel, gene_list = gene_list,
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_rel-mhcII_genes", 5, 5)

# diagonstic vs. late relapse
res <- getLR(de.df = de.diag_v_late_rel, gene_list = gene_list,
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_late_rel-mhcII_genes", 5, 5)

# HL vs. RLN
res <- getLR(de.df = de.hl_vs_rln, gene_list = gene_list,
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-hl_vs_rln-mhcII_genes", 5, 5)

# ##################################################
# LR interactions for CXC genes
# ##################################################

GOI <- c("CXCR3", "CXCL12", "CXCL13")

res <- getLR(de.df = de.diag_v_refractory, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_refractory-CXC_genes", 5, 5)

res <- getLR(de.df = de.diag_v_early_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_early_rel-CXC_genes", 5, 5)

res <- getLR(de.df = de.diag_v_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_rel-CXC_genes", 5, 5)

res <- getLR(de.df = de.diag_v_late_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_late_rel-CXC_genes", 5, 5)

res <- getLR(de.df = de.hl_vs_rln, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-hl_vs_rln-CXC_genes", 5, 5)


# ##################################################
# LR interactions for GOI
# ##################################################

GOI <- c("CD80", "CD86", "CD274", "CD80", "CD86", "IGF2R", "M6PR", "FGL1", "CLEC4G", "LGALS3", "CD274", "PDCD1LG2", "LGALS9", "HMGB1", "CEACAM1", "PTDSS1")

res <- getLR(de.df = de.diag_v_refractory, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_refractory-GOI", 5, 5)

res <- getLR(de.df = de.diag_v_early_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_early_rel-GOI", 5, 5)

res <- getLR(de.df = de.diag_v_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_rel-GOI", 5, 5)

res <- getLR(de.df = de.diag_v_late_rel, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-diag_vs_late_rel-GOI", 5, 5)

res <- getLR(de.df = de.hl_vs_rln, 
             gene_list = GOI, 
             file_name_prefix = "~/Documents/sc_HL_relapse/seurat/figures/LATEST/iTALK/LRPlot-hl_vs_rln-GOI", 5, 5)

```
